#!/bin/bash

module load ants

OUT_PATH='/home/mpib/nemecz/Projects/miniTRK/Results/01_MRI/ANTS_REG'
T1_PATH='/home/mpib/nemecz/Projects/miniTRK/Results/01_MRI/BrainExtraction'
COPE='/home/mpib/nemecz/Projects/miniTRK/Results/01_MRI/fMRI_ThirdLevel/%VERSION_OUT%/%TASK%_LURE-FIRST_VS_ERP-FIRST.gfeat'
COPE_OUT='/home/mpib/nemecz/Projects/miniTRK/Results/01_MRI/fMRI_ThirdLevel/%VERSION_OUT%/%TASK%_LURE-FIRST_VS_ERP-FIRST.gfeat'

## 1. Clster masks
antsApplyTransforms \
-d 3 \
-i ${COPE}/cope1.feat/cluster_mask_zstat%COPE_NUMBER%.nii.gz \
-o ${COPE_OUT}/MNI_LURE-FIRST_vs_ERP-FIRST_cluster_mask_zstat%COPE_NUMBER%.nii.gz.nii.gz \
-n GenericLabel \
-r ${OUT_PATH}/MNI152_T1_1mm_brain.nii.gz \
-t ${OUT_PATH}/T1_to_MNI/GroupTempl/GroupTempl_T1-To-MNI_0GenericAffine.mat \
-t ${OUT_PATH}/T1_to_MNI/GroupTempl/GroupTempl_T1-To-MNI_1Warp.nii.gz

## Thresholded zstat
antsApplyTransforms \
-d 3 \
-i ${COPE}/cope1.feat/thresh_zstat%COPE_NUMBER%.nii.gz \
-o ${COPE_OUT}/MNI_LURE-FIRST_vs_ERP-FIRST_thresh_zstat%COPE_NUMBER%.nii.gz \
-r ${OUT_PATH}/MNI152_T1_1mm_brain.nii.gz \
-t ${OUT_PATH}/T1_to_MNI/GroupTempl/GroupTempl_T1-To-MNI_0GenericAffine.mat \
-t ${OUT_PATH}/T1_to_MNI/GroupTempl/GroupTempl_T1-To-MNI_1Warp.nii.gz
